- name: Configure syslog
  lineinfile:
    dest: '{{ rsyslog_config_path }}'
    regexp: ^\*\.\*
    line: '*.* @{{ansible_default_ipv4.address}}:5000'

- name: Restart rsyslog
  service: name=rsyslog state=restarted